FROM docker.io/arm64v8/debian:10.6
ARG cvmfsversion=2.8.0
ARG cvmfsconfigversion=0.2.3

RUN apt-get update -y && \
  apt-get install -y wget lsb-release

RUN wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb &&  \
  dpkg -i cvmfs-release-latest_all.deb && \
  rm -f cvmfs-release-latest_all.deb

RUN apt-get install -y debhelper autotools-dev cmake cpio libcap-dev libssl-dev pkg-config libattr1-dev patch \
  python-dev python-setuptools unzip uuid-dev valgrind libz-dev gawk psmisc autofs curl attr zlib1g gdb uuid-dev \
  uuid adduser autofs psmisc curl attr openssl libcap2 libcap2-bin lsof rsync jq usbutils sqlite3 sudo \
  fuse libfuse-dev libfuse2 libfuse3-dev

# build CernVM-FS from source (no aarch64 Debian packages available)
RUN apt-get install sudo && \
  wget https://github.com/cvmfs/cvmfs/archive/cvmfs-${cvmfsversion}.tar.gz && \
  tar xfz cvmfs-${cvmfsversion}.tar.gz && \
  cd cvmfs*${cvmfsversion}/ && \
  mkdir build && \
  cd build && \
  cmake .. -DBUILD_SERVER=no -DBUILD_SERVER_DEBUG=no -DDBUILD_SHRINKWRAP=no && \
  make -j $(nproc) && \
  sudo make install && \
  cd / && \
  rm -r cvmfs*${cvmfsversion}*

RUN wget https://github.com/EESSI/filesystem-layer/releases/download/v${cvmfsconfigversion}/cvmfs-config-eessi_${cvmfsconfigversion}_all.deb && \
  dpkg -i cvmfs-config-eessi_${cvmfsconfigversion}_all.deb && \
  rm -f cvmfs-config-eessi_${cvmfsconfigversion}_all.deb

# install fuse3 so Singularity's --fusemount works
# (can't be installed together with fuse)
RUN apt-get remove -y fuse && apt-get install -y fuse3

RUN apt-get install -y fuse-overlayfs

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local && \
  echo 'CVMFS_HTTP_PROXY="DIRECT"' >> /etc/cvmfs/default.local

ENV LC_ALL=C
