# At the moment this script will only filter out the easystack files
# Next step could be to filter out other subpaths 
# by using the GITHUB action envitonment variables and passing them to this python script.

# Can also distiguish between modified, added files
# That information is in the string that is generated by git diff
# For filtering out changed easystacks this was however not required

import os

diff = os.getenv('CHANGED')
env_file = os.getenv('GITHUB_ENV')

diff_list = diff.split('\n')

diff_filter_path = 'easystacks'

diff_filtered = ''

for line in diff_list:
    status = line.split('\t')[0]
    file = line.split('\t')[1] 
    if file.startswith(diff_filter_path):
        # Ignoring the status assigned to the file
        diff_filtered += file + ' '

# If we will at some point add paths to in diff_filter_path
# we'll have to remove '/'
env_var = 'CHANGED_' + diff_filter_path.upper()
set_var = env_var + "=" + diff_filtered

with open(env_file, 'a') as file:
    file.write(set_var)
