# At the moment this script will only filter out the easystack files
# Next step could be to filter out other subpaths 
# by using the GITHUB action environment variables and argsparse.

# Can also distiguish between modified, added, ... files
# That information is in the string that is generated by git diff
# For filtering easystacks this was however not necessary 
# since we want to check both added and modified files

# Todo: This script should eventually be its own github action. When it can be used for filtering more files. And all the todo have been addressed.

import os

diff = os.getenv('CHANGED')
env_file = os.getenv('GITHUB_ENV')

diff_list = diff.split('\n')

diff_filter_path = 'easystacks'

diff_filtered = ''

for line in diff_list:
    status = line.split('\t')[0]
    file = line.split('\t')[1] 
    if file.startswith(diff_filter_path):
        # Ignoring the status assigned to the file
        diff_filtered += file + ' '

if diff_filtered != '':
    # Todo: Can only handle 1 level paths now
    # If we want to pass multi-level paths this will need to be updated
    # Name of the env_var can change based on the file or path
    env_var = 'CHANGED_' + diff_filter_path.upper()
    set_var = env_var + "=" + diff_filtered

    # This adds the environment variable to the github action environment
    with open(env_file, 'a') as file:
        file.write(set_var)
