name: Create Check Run
on:
  push:
    branches: [ "*-software.eessi.io" ]
  pull_request:
permissions:
  contents: read
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  build_check:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        EESSI_VERSION:
        - 2023.06
        EESSI_SOFTWARE_SUBDIR_OVERRIDE:
        - aarch64/generic
        #- aarch64/neoverse_n1
        #- aarch64/neoverse_v1
        #- x86_64/amd/zen2
        #- x86_64/amd/zen3
        #- x86_64/amd/zen4
        #- x86_64/intel/haswell
        #- x86_64/intel/sapphirerapids
        #- x86_64/intel/skylake_avx512
        - x86_64/generic
    steps:
        - name: Create Check
          run: |
            curl -L -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GH_TOKEN"\
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository }}/check-runs \
             -d '{"name":"A Mighty Test", "head_sha":"${{ github.event.pull_request.head.sha }}", "status":"in_progress","output":{"title":"A Mighty Summary"}}'
