# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Test new action
on:
  push:
    branches: [ "*-software.eessi.io" ]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read # to fetch code (actions/checkout)
env:
  EESSI_ACCELERATOR_TARGETS: |
    x86_64/amd/zen2:
      - nvidia/cc80
    x86_64/amd/zen3:
      - nvidia/cc80
jobs:
  check_missing:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        EESSI_VERSION:
        - 2023.06
        EESSI_SOFTWARE_SUBDIR_OVERRIDE:
        - x86_64/amd/zen2
        - x86_64/amd/zen3
        - x86_64/amd/zen4
        - x86_64/intel/haswell
        - x86_64/intel/skylake_avx512
        - x86_64/generic
    steps:
        - name: Check out software-layer repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - name: find changed easystacks
          run: |
            echo "GITHUB_HEAD_REF = ${GITHUB_HEAD_REF}"
            echo "GITHUB_BASE_REF = ${GITHUB_BASE_REF}"
            echo $GITHUB_ENV
            export CHANGED=test
            echo "CHANGED={$CHANGED}" >> $GITHUB_ENV
        - name: Are there changed files
          run: |
            echo $CHANGED
            echo $GITHUB_ENV
#        - name: Mount EESSI CernVM-FS pilot repository
#          uses: cvmfs-contrib/github-action-cvmfs@55899ca74cf78ab874bdf47f5a804e47c198743c # v4.0
#          with:
#              cvmfs_config_package: https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
#              cvmfs_http_proxy: DIRECT
#              cvmfs_repositories: software.eessi.io
#        - name: find changed easystacks
#          uses: laraPPr/test_easystack_filter_action@0c1cb269a89654084c59308e40ae92e90c854fba
#          uses: dorny/paths-filter@v3
#          id: changes
#          with:
#            list-files: shell
#            filters: |
#              changed:
#                - 'easystacks/**'
